function filename = trialfile(trialno, namebase, suffix, fileext, extdel)
% TRIALFILE is a convenient function to compose filenames from trial numbers.
%           TAPADM works with a 4-digits file pattern, like in '0001.amp'
%           which will be generated by:    trialfile(1, '', '', 'amp') 
%           
%           All arguments besides of the trial number are optional.
%           The function returns: 
%           [namebase num2str(trialno, '%04d') suffix extdel fileext] 
%            
%           filename = trialfile(trialno, namebase, suffix, fileext, extdel)
%
%   SEE ALSO FULLFILE

%---------------------------------------------------------------------
% Copyright © 2007 by Andreas Zierdt (Anderas.Zierdt@phonetik.uni-muenchen.de)
% 
% This program is free software; you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the 
% Free Software Foundation; either version 2 of the License, or (at your option) 
% any later version.
%
% This program is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along with 
% this program; if not, write to the Free Software Foundation, Inc., 
% 51 Franklin Street, Fifth Floor, Boston, MA 
%---------------------------------------------------------------------
error(nargchk(1, 5, nargin));

if (trialno < 0)
	error('trial number must not be negative'); 	
end	

if (trialno > 9999)
	error('trial number too large (more than 4 digits)'); 	
end	

if (nargin < 5)
	extdel = '.'; 								% default delemiter for file extension
end	

if (nargin < 4)								% default file extension
	fileext = '.mat'; 	
else
	deblank(fileext);							% remove trailing blanks 
	if (strcmp(fileext, extdel)~=1)		% if not allready specified, 
		fileext = [extdel fileext];		% insert extension delemiter
	end
end	
if (nargin < 3)
	suffix = ''; 	
end	
if (nargin < 2)
	namebase = ''; 	
end	

filename = [namebase num2str(trialno, '%04d') suffix fileext];
